### ISSUE TITLE
error[E0425]: cannot find function `parse_doc` in crate `xpather`

### ISSUE THREAD

**Issue by DmitrySorda** [Its-its/xpath-scraper#1]
1)
let document = xpather::parse_doc(&mut Cursor::new(data)); -- not found in `xpather`
2)
error[E0599]: no method named `convert_from` found for enum `Result` in the current scope
`help: use scraper_main::ConvertToValue;`

**Comment by Its-its** [comment]
Edit: It looks like I didn't update the README. it should be `xpather::parse_document` or `scraper_main::xpather::parse_document` either one. The [example](/Its-its/xpath-scraper/tree/main/example) is updated and working though.

Hello! The error tells you that you need to import the `scraper_main::ConvertToValue` trait You can take a look at the example to have a working one.

Along with that the only dependency you need is `scraper-main = "0.3.0"`

**Comment by DmitrySorda** [comment]
All corrected. Example worked.
Thanks
